[package]
name = "howmanysmall/better-signal"
version = "2.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A slightly modified Signal library."
license = "MIT"
exclude = [
	".gitignore",
	"sourcemap.json",
	"*.yml",
	"*.code-workspace",
	".lune",
	"build",
	"docs",
	".vscode",
	"*.toml",
	"test.project.json",
	"scripts",
	"lua",
	"Packages",
	"DevPackages",
	"*.rbxlx.lock",
	"*.rbxl.lock",
	"**/*.rbx[lm]*",
	"dist",
	"**/__tests__",
	"**/jest.config.luau",
]
include = ["src", "wally.toml"]

[dependencies]

[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"
